# .github/release.yml

changelog:
  exclude:
      labels:
        - wontfix
        - duplicate
  categories:
    - title: "🚀 Features"
      labels:
        - feature
        - enhancement

    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
        - bugfix

    - title: "🛠 Maintenance & Refactoring"
      labels:
        - refactor
        - chore
        - cleanup

    - title: "📖 Documentation"
      labels:
        - docs
        - documentation

    - title: "🔧 Dependency Updates"
      labels:
        - dependencies
        - upgrade
