# .github/release.yml

changelog:
  exclude:
      labels:
        - wontfix
        - duplicate

  categories:
    - title: "🚀 Features"
      labels:
        - feature
        - enhancement

    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix

    - title: "🛠 Maintenance & Refactoring"
      labels:
        - refactor
        - cleanup

    - title: "📖 Documentation"
      labels:
        - docs
        - documentation

    - title: "🔧 Dependency Updates"
      labels:
        - dependencies

    - title: "Other Changes"
      labels: ["*"]
