services:
  reaspeech-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
      args:
        - SERVICE_UID
        - SERVICE_GID
    entrypoint: ["python3", "app/run.py", "--build-reascripts"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - ASR_ENGINE=faster_whisper
      - ENABLE_SWAGGER_UI=/docs
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app/app
      - ./reascripts:/app/reascripts
      - cache-pip:/root/.cache/pip
      - cache-whisper:/root/.cache/whisper

volumes:
  cache-pip:
  cache-whisper:
