services:
  reaspeech:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_UID
        - SERVICE_GID
    entrypoint: ["python3", "app/run.py", "--build-reascripts", "--build-reascripts-target=all"]
    environment:
      - ASR_ENGINE=faster_whisper
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app/app
      - ./reascripts:/app/reascripts
      - cache-pip:/root/.cache/pip
      - cache-whisper:/root/.cache/whisper

volumes:
  cache-pip:
  cache-whisper:
