name: Feature Request
description: It doesn't hurt to ask.
title: "[feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### Feature Request
        What would you like to see added to the project?
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: The more detail you provide, the better.
    validations:
      required: true
  - type: textarea
    id: feature_use_case
    attributes:
      label: Use Case
      description: How would you use this feature? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: feature_additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: true
