name: Lint & Test ReaScripts

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.3", "5.4"]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: reascripts

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@v4

    - name: setup 
      run: |
        luarocks install luacheck

    - name: test
      run: |
        make